# Moneydance extension build system
# The /userconfig/ folder and its file(s) belongs to the Moneydance Open project which is used to compile, package, and sign extensions.
# These files are used by gradle (wrapper) during the build process. The gradle files are contained in both the project's root, and "/gradle" folder.
# "user.gradle.properties" is a user-specific file that overrides settings used during the gradle build process

# set your own secret passphrase below (replace the word secret) and run "./gradlew genKeys" from project root folder to create the "priv_key" and "pub_key" files before attempting any build.
keypass=secret

# advanced - optionally uncomment the "md_ext_lib_dir" setting below, suppling a path containing a full set of Moneydance jars that will override the standard /lib/ build jars.
#md_ext_lib_dir=path
